import { test } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/setup');
  await page.getByRole('spinbutton', { name: 'Количество участников:' }).click();
  await page.getByRole('spinbutton', { name: 'Количество участников:' }).fill('8');
  await page.getByRole('spinbutton', { name: 'Количество туров:' }).click();
  await page.getByRole('spinbutton', { name: 'Количество туров:' }).fill('3');
  await page.getByRole('textbox', { name: 'Имя' }).click();
  await page.getByRole('textbox', { name: 'Имя' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Имя' }).fill('А');
  await page.getByRole('textbox', { name: 'Имя' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Имя' }).fill('Александр');
  await page.getByRole('textbox', { name: 'Фамилия' }).click();
  await page.getByRole('textbox', { name: 'Фамилия' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Фамилия' }).fill('П');
  await page.getByRole('textbox', { name: 'Фамилия' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Фамилия' }).fill('Пушкин');
  await page.getByPlaceholder('Рейтинг').click();
  await page.getByPlaceholder('Рейтинг').fill('1724');
  await page.getByRole('button', { name: 'Добавить' }).click();
  await page.getByRole('textbox', { name: 'Имя' }).click();
  await page.getByRole('textbox', { name: 'Имя' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Имя' }).fill('М');
  await page.getByRole('textbox', { name: 'Имя' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Имя' }).fill('Максим');
  await page.getByRole('textbox', { name: 'Фамилия' }).click();
  await page.getByRole('textbox', { name: 'Фамилия' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Фамилия' }).fill('В');
  await page.getByRole('textbox', { name: 'Фамилия' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Фамилия' }).fill('Велижанин');
  await page.getByPlaceholder('Рейтинг').click();
  await page.getByRole('textbox', { name: 'Фамилия' }).click();
  await page.getByRole('textbox', { name: 'Фамилия' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Фамилия' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Фамилия' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Фамилия' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Фамилия' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Фамилия' }).fill('Великжанин');
  await page.getByPlaceholder('Рейтинг').click();
  await page.getByPlaceholder('Рейтинг').fill('1500');
  await page.getByRole('button', { name: 'Добавить' }).click();
  await page.getByRole('textbox', { name: 'Имя' }).click();
  await page.getByRole('textbox', { name: 'Имя' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Имя' }).fill('Т');
  await page.getByRole('textbox', { name: 'Имя' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Имя' }).fill('Тимур');
  await page.getByRole('textbox', { name: 'Фамилия' }).click();
  await page.getByRole('textbox', { name: 'Фамилия' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Фамилия' }).fill('Т');
  await page.getByRole('textbox', { name: 'Фамилия' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Фамилия' }).fill('Турдышев');
  await page.getByPlaceholder('Рейтинг').click();
  await page.getByPlaceholder('Рейтинг').fill('2000');
  await page.getByRole('button', { name: 'Добавить' }).click();
  await page.getByRole('textbox', { name: 'Имя' }).click();
  await page.getByRole('textbox', { name: 'Имя' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Имя' }).fill('Л');
  await page.getByRole('textbox', { name: 'Имя' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Имя' }).fill('Леонель');
  await page.getByRole('textbox', { name: 'Фамилия' }).click();
  await page.getByRole('textbox', { name: 'Фамилия' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Фамилия' }).fill('М');
  await page.getByRole('textbox', { name: 'Фамилия' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Фамилия' }).fill('Месси');
  await page.getByPlaceholder('Рейтинг').click();
  await page.getByPlaceholder('Рейтинг').fill('1806');
  await page.getByRole('button', { name: 'Добавить' }).click();
  await page.getByText('Добавить участника (4/8)Добавить').click();
  await page.getByRole('textbox', { name: 'Имя' }).click();
  await page.getByRole('textbox', { name: 'Имя' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Имя' }).fill('И');
  await page.getByRole('textbox', { name: 'Имя' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Имя' }).fill('Иван ');
  await page.getByRole('textbox', { name: 'Фамилия' }).click();
  await page.getByRole('textbox', { name: 'Фамилия' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Фамилия' }).fill('И');
  await page.getByRole('textbox', { name: 'Фамилия' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Фамилия' }).fill('Иванов');
  await page.getByPlaceholder('Рейтинг').click();
  await page.getByPlaceholder('Рейтинг').fill('1563');
  await page.getByRole('button', { name: 'Добавить' }).click();
  await page.getByRole('textbox', { name: 'Имя' }).click();
  await page.getByRole('textbox', { name: 'Имя' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Имя' }).fill('Е');
  await page.getByRole('textbox', { name: 'Имя' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Имя' }).fill('Евгений');
  await page.getByRole('textbox', { name: 'Фамилия' }).click();
  await page.getByRole('textbox', { name: 'Фамилия' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Фамилия' }).fill('О');
  await page.getByRole('textbox', { name: 'Фамилия' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Фамилия' }).fill('Онегин');
  await page.getByPlaceholder('Рейтинг').click();
  await page.getByPlaceholder('Рейтинг').fill('1666');
  await page.getByRole('button', { name: 'Добавить' }).click();
  await page.getByRole('textbox', { name: 'Имя' }).click();
  await page.getByRole('textbox', { name: 'Имя' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Имя' }).fill('Ю');
  await page.getByRole('textbox', { name: 'Имя' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Имя' }).fill('Юра');
  await page.getByRole('textbox', { name: 'Фамилия' }).click();
  await page.getByRole('textbox', { name: 'Фамилия' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Фамилия' }).fill('П');
  await page.getByRole('textbox', { name: 'Фамилия' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Фамилия' }).fill('');
  await page.getByRole('textbox', { name: 'Имя' }).click();
  await page.getByRole('textbox', { name: 'Имя' }).fill('');
  await page.getByRole('textbox', { name: 'Имя' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Имя' }).fill('Д');
  await page.getByRole('textbox', { name: 'Имя' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Имя' }).fill('Дмитрий');
  await page.getByRole('textbox', { name: 'Фамилия' }).click();
  await page.getByRole('textbox', { name: 'Фамилия' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Фамилия' }).fill('Н');
  await page.getByRole('textbox', { name: 'Фамилия' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Фамилия' }).fill('Нагиев');
  await page.getByPlaceholder('Рейтинг').click();
  await page.getByPlaceholder('Рейтинг').fill('1993');
  await page.getByRole('button', { name: 'Добавить' }).click();
  await page.getByRole('textbox', { name: 'Имя' }).click();
  await page.getByRole('textbox', { name: 'Имя' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Имя' }).fill('Н');
  await page.getByRole('textbox', { name: 'Имя' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Имя' }).fill('Никита');
  await page.getByRole('textbox', { name: 'Фамилия' }).click();
  await page.getByRole('textbox', { name: 'Фамилия' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Фамилия' }).fill('Д');
  await page.getByRole('textbox', { name: 'Фамилия' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Фамилия' }).fill('Дубровский');
  await page.getByPlaceholder('Рейтинг').click();
  await page.getByPlaceholder('Рейтинг').fill('1778');
  await page.getByRole('button', { name: 'Добавить' }).click();
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('button', { name: 'Туры' }).click();
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.locator('div').filter({ hasText: /^Тимур ТурдышевvsДмитрий НагиевВыберите результатПобеда ТимурПобеда ДмитрийНичья$/ }).getByRole('combobox').selectOption('win1');
  await page.getByRole('combobox').nth(1).selectOption('draw');
  await page.getByRole('combobox').nth(2).selectOption('win1');
  await page.getByRole('combobox').nth(3).selectOption('win2');
  await page.getByRole('button', { name: 'Следующий тур' }).click();
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('combobox').first().selectOption('win1');
  await page.getByRole('combobox').nth(1).selectOption('win2');
  await page.getByRole('combobox').nth(2).selectOption('draw');
  await page.getByRole('combobox').nth(3).selectOption('win1');
  await page.getByRole('button', { name: 'Следующий тур' }).click();
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.locator('div').filter({ hasText: /^Тимур ТурдышевvsЛеонель МессиВыберите результатПобеда ТимурПобеда ЛеонельНичья$/ }).getByRole('combobox').selectOption('win2');
  await page.getByRole('combobox').nth(1).selectOption('win1');
  await page.getByRole('combobox').nth(2).selectOption('win2');
  await page.getByRole('combobox').nth(3).selectOption('win1');
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('button', { name: 'Завершить турнир' }).click();
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('button', { name: 'Положение' }).click();
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('button', { name: 'Тур 2' }).click();
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('button', { name: 'Тур 3' }).click();
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('button', { name: 'Пары' }).click();
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('button', { name: 'Тур 1' }).click();
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('button', { name: 'Тур 2' }).click();
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('button', { name: 'Тур 3' }).click();
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('button', { name: 'Общая таблица' }).click();
  
});